spring.application.name=UserRegisterAppli

spring.datasource.url=jdbc:mysql://mysql-3c4a2073-mannambhavana313-bb09.i.aivencloud.com:26644/defaultdb?sslMode=REQUIRED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:9098}